language: cpp
compiler: clang

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - python-sphinx

before_install:
  - pip install --user cpp-coveralls
  - pip install --user breathe

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ..

script:
  - cd build
  - cmake --build .
  - ctest .
  - cd ..
  - cd doc
  - doxygen
  - make html
  - cd ..

after_success:
  - coveralls --exclude build/CMakeFiles/ --gcov "llvm-cov gcov" --gcov-options '\-lp'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: doc/_build/html
  on:
    branch: master